### ISSUE TITLE
can't test function that with default params

### ISSUE THREAD

**Issue by happysong** [ponicode/ponicode.github.io#3]
```
export function bool (val, truthy = 'yes', falsey = 'no') {
  if (typeof val === 'string') {
    return (val && val !== '0') ? truthy : falsey;
  }
  return val ? truthy : falsey;
}

```

**Comment by bbouffaut** [comment]
Hello @happysong . I'm very sorry about the (very) late answer. Many thanks for your feedback. We didn't expect to receive feedback on there. Since the time, we implemented the support of such kind of syntax. It works perfectly well now. Let us know if you have any other questions / feedback. Many thanks again.

![Screenshot from 2021-11-30 17-23-51](https://user-images.githubusercontent.com/7842724/144086986-c4d5b2f1-0be3-405e-9ab3-c912125beb03.png)
